# Generated by Django 5.1.1 on 2024-10-04 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conferences_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferences',
            options={'verbose_name_plural': 'conferences'},
        ),
        migrations.AddField(
            model_name='conferences',
            name='capacity',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(limit_value=900, message='capacity must be under 900')]),
        ),
        migrations.AddField(
            model_name='conferences',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
