# Generated by Django 5.1.1 on 2024-10-11 08:42

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_title'),
        ('conferences', '0003_alter_conferences_options_conferences_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferences',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conferences',
            name='program',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'], message='Only pdf, png, jpeg, jpg allowed')]),
        ),
        migrations.AlterField(
            model_name='conferences',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='conferences',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gte', datetime.date(2024, 10, 11))), name='The start date must be greater than today or equal'),
        ),
    ]
