# Generated by Django 5.1.1 on 2024-10-04 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', 'Only letters are allowed')]),
        ),
    ]
