# Generated by Django 5.1.1 on 2024-10-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PingWeb', '0001_initial'),
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='reservations',
            field=models.ManyToManyField(related_name='reservations', through='PingWeb.Reservation', to='conferences.conferences'),
        ),
    ]
