# Generated by Django 5.1.1 on 2024-10-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PingWeb', '0002_participant_reservations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name_plural': 'participants'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'reservations'},
        ),
    ]
